<?php

namespace OfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnakRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnakRepository extends EntityRepository
{
}
