<?php

namespace OfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OfficeBundle\Contracts\Repository\AttachmentInterface;
use OfficeBundle\Entity\Attachment;

/**
 * AttachmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentRepository extends EntityRepository implements AttachmentInterface
{
    /**
     * @param $id
     *
     * @return Attachment
     */
    public function findById($id)
    {
        return $this->find($id);
    }

    /**
     * @param $userId
     *
     * @return Attachment
     */
    public function findByUserId($userId)
    {
        return $this->findOneBy(['userId' => $userId]);
    }
}
