<?php

namespace OfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DayTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayTypeRepository extends EntityRepository
{
}
