<?php

namespace OfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OfficeBundle\Contracts\Repository\UserPersonalInterface;
use OfficeBundle\Entity\UserPersonal;

/**
 * UserPersonalRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPersonalRepository extends EntityRepository implements UserPersonalInterface
{
    /**
     * @param $id
     *
     * @return UserPersonal
     */
    public function findById($id)
    {
        return $this->find($id);
    }

    /**
     * @param $nik
     *
     * @return UserPersonal
     */
    public function findByNik($nik)
    {
        return $this->findOneBy(['nik' => $nik]);
    }

    /**
     * @param $username
     *
     * @return UserPersonal
     */
    public function findByUsername($username)
    {
        return $this->findOneBy(['username' => $username]);
    }

    /**
     * @param $email
     *
     * @return UserPersonal
     */
    public function findByEmail($email)
    {
        return $this->findOneBy(['email' => $email]);
    }

    /**
     * @param $penempatan
     *
     * @return UserPersonal
     */
    public function findByPenempatan($penempatan)
    {
        return $this->findBy(['penempatan' => $penempatan]);
    }
}
