<?php

namespace OfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OfficeBundle\Contracts\Repository\UserFamilyInterface;
use OfficeBundle\Entity\UserFamily;

/**
 * UserFamilyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFamilyRepository extends EntityRepository implements UserFamilyInterface
{
    /**
     * @param $id
     *
     * @return UserFamily
     */
    public function findById($id)
    {
        return $this->find($id);
    }

    /**
     * @param $userId
     *
     * @return UserFamily
     */
    public function findByUserId($userId)
    {
        return $this->findOneBy(['userId' => $userId]);
    }
}
