<?php

namespace OfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OfficeBundle\Contracts\Repository\UserJobInterface;
use OfficeBundle\Entity\UserJob;

/**
 * UserJobRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserJobRepository extends EntityRepository implements UserJobInterface
{
    /**
     * @param $id
     *
     * @return UserJob
     */
    public function findById($id)
    {
        return $this->find($id);
    }

    /**
     * @param $userId
     *
     * @return UserJob
     */
    public function findByUserId($userId)
    {
        return $this->findOneBy(['userId' => $userId]);
    }
}
