office_admin_fingerprint_dummy:
    path: /dummy
    defaults:
        _controller: OfficeBundle:Fingerprint:dummy

office_fingerprint_presence:
    path: /presence
    defaults:
        _controller: OfficeBundle:Fingerprint:presence

office_fingerprint_presence_process:
    path: /presence-process
    defaults:
        _controller: OfficeBundle:Fingerprint:presenceProcess

office_fingerprint_delete_user:
    path: /delete/{user_id}
    defaults:
        _controller: OfficeBundle:Fingerprint:deleteUser
